# Generated by Django 6.1 on 2026-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=20)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('joined_at', models.DateField()),
            ],
        ),
    ]
